name: Hardcoded Secrets Detection

on:
  push:
    branches:
      - main

jobs:
  install-gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitLeaks
        run: |
          curl -sSfL https://install.goreleaser.com/github.com/zricethezav/gitleaks.sh | sudo bash

      - name: Set up environment
        run: echo "PATH=\$HOME/.local/bin:\$PATH" >> $GITHUB_ENV

  gitleaks-check:
    needs: install-gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run GitLeaks (First Run)
        id: gitleaks-first-run
        run: |
          gitleaks --path=. --verbose > gitleaks_output_first_run.txt

  # Add your build and test steps here if needed

  gitleaks-check-again:
    needs: install-gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run GitLeaks (Second Run)
        id: gitleaks-second-run
        run: |
          gitleaks --path=. --verbose > gitleaks_output_second_run.txt

      - name: Concatenate Outputs
        run: cat gitleaks_output_first_run.txt gitleaks_output_second_run.txt > all_gitleaks_output.txt

      - name: Display All Secrets
        run: cat all_gitleaks_output.txt
